# Generated by Django 5.2.5 on 2025-08-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_oferecidos', to='profissionais.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais_do_servico', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Serviço de Profissional',
                'verbose_name_plural': 'Serviços de Profissionais',
                'unique_together': {('profissional', 'servico')},
            },
        ),
    ]
